version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: animal-image-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:animaldb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - ./tmp:/tmp
    networks:
      - animal-service-network

networks:
  animal-service-network:
    driver: bridge